# =======================================
# macros.jl -- helper macros for grammars
# =======================================

using MacroTools: @capture, postwalk, rmlines

public @syntax, @semantics

function find_pikaparser(__module__)
    localmods  = [name for name in names(__module__, imported=true)
                    if @eval(__module__,
                        try
                            $name isa Module
                        catch e
                            false
                        end)]
    return [mod for mod in localmods
            if @eval(__module__, nameof($mod) == :PikaParser)][1]
end

# internal helper function to rewrite regex to scan clauses
function prepare_regex_expr(regexstr, P)

    # pull out the regex string and its args
    regex, args = length(regexstr) > 1 ?
        (regexstr[1], regexstr[2]) :
        (regexstr[1], nothing)

    # force a '^' at the regex start
    regex = regex[1] == '^' ?
        regex : "^" * regex

    # compile the regex
    r = isnothing(args) ?
        Regex(regex) :
        Regex(regex, args)

    # produce the scan clause.
    @gensym x matched
    return quote
        $P.scan($x -> begin
            $matched = match($r, $x)
            isnothing($matched) && return 0
            return length($matched.match)
        end)
    end
end


"""
    @syntax startrule datatype exprs

Define syntax of a grammar with rules given by "exprs".

This produces a PikaParser grammar at compile-time,
and returns a function applying the grammar to
an input string.

An example invocation is given herein.

```julia
syn = P.@syntax :top begin
    :ws    => first(satisfy(isspace), epsilon)
    :ident => r"[a-z_]+[a-z0-9_]*"i
    :decl  => seq(:ident, :ws)
    :top   => some(:decl)
end

syn("foo Bar bA9Z QUx") # => PikaParser.ParserState
```

This returned function composes with the function
generated by @semantics to produce a complete parse:

```julia
sem = P.@semantics :top m v begin
    :ident => Symbol(m.view)
    :decl  => v[1]
end

syn("foo Bar bA9Z QUx") |> sem
    # => [:foo, :Bar, :bA9Z, :QUx]
```
"""
macro syntax(startrule, datatype, exprs)

    ids, clauses = [], []
    @gensym x

    P = find_pikaparser(__module__)
    pika_syms = Dict(
        :satisfy            => :($P.satisfy           ),
        :scan               => :($P.scan              ),
        :token              => :($P.token             ),
        :tokens             => :($P.tokens            ),
        :epsilon            => :($P.epsilon           ),
        :fail               => :($P.fail              ),
        :seq                => :($P.seq               ),
        :first              => :($P.first             ),
        :not_followed_by    => :($P.not_followed_by   ),
        :followed_by        => :($P.followed_by       ),
        :some               => :($P.some              ),
        :many               => :($P.many              ),
        :tie                => :($P.tie               ),
        :precedence_cascade => :($P.precedence_cascade),
    )

    # process the expressions.
    postwalk(exprs) do e

        # remove line number nodes.
        e = rmlines(e)

        # rewrite names
        e isa Symbol && return get(pika_syms, e, e)

        # rules for maybe()
        @capture(e, maybe(expr__)) && return quote
            $P.first($(expr...), $P.epsilon)
        end

        # rules for regex string (continue if no match)
        @capture(e, @r_str regexstr__) &&
            return prepare_regex_expr(regexstr, P)

        # return if we don't have a toplevel rule
        @capture(e, id_quote => clause_) ||
            return e

        # store the id and clause; return the ID
        push!(ids, id)
        push!(clauses, clause)
        return id
    end

    # Evaluate quotenodes and build clauses in
    # calling-module context.
    pairs = map(zip(ids, clauses)) do (id, clause)
        @eval(__module__, $id) => @eval(__module__, $clause)
    end

    startrule = @eval(__module__, $startrule)
    startrule = startrule isa Symbol ?
        [startrule] :
        startrule

    # build the grammar.
    g = make_grammar(
        startrule,
        flatten(
            @eval(__module__, Dict($pairs...)),
            @eval(__module__, $datatype)
        )
    )

    return quote 
        $x -> $P.parse($g, $x)
    end |> esc
end

macro syntax(startrule, expr)
    P = find_pikaparser(__module__)
    return quote 
        $P.@syntax($startrule, Char, $expr)
    end |> esc
end

"""
    @semantics startrule datatype exprs

Define semantics of a grammar with rules given by "exprs".

This macro returns a function which can be applied to a
ParserState object, returning Julia datatypes as
defined by the semantic rules.

An example invocation is given here.

```julia
sem = P.@semantics :top m v begin
    :ident => Symbol(m.view)
    :decl  => v[1]
end

```

The function returned from this macro composes with the
function returned by the "@syntax" macro; they are intended
to be used together. To continue this example:

```julia
syn = P.@syntax :top begin
    :ws    => first(satisfy(isspace), epsilon)
    :ident => r"[a-z_]+[a-z0-9_]*"i
    :decl  => seq(:ident, :ws)
    :top   => some(:decl)
end

syn("foo Bar bA9Z QUx") |> sem
    # => [:foo, :Bar, :bA9Z, :QUx]
```
"""
macro semantics(top, match, submatches, exprs)

    rules, x = Expr[], gensym(:x)
    P = find_pikaparser(__module__)

    # process the semantic rules.
    postwalk(exprs) do e

        # match expressions of the form (symbol) => (rule)
        @capture(e, rule_quote => value_) || return e

        # rewrite semantic rule as if-statement.
        push!(rules, quote 
            if $match.rule == $rule
                $value
            else
                $submatches == [] ?
                    $match.view :
                    $submatches
            end
        end)

        return e
    end

    # rewrite the AST to chain the if statements.
    rules = reduce(reverse(rules)) do r1, r2
        r2.args[2].args[3] = r1
        r2
    end

    # generate the fold function.
    return quote
        $x -> $P.traverse_match($x,
            $P.find_match_at!($x, $top, 1),
            fold = ($match, _, $submatches) -> $rules
        )
    end |> esc
end
