# =======================================
# macros.jl -- helper macros for grammars
# =======================================

using MacroTools: @capture, postwalk, rmlines

public @syntax, @semantics

# internal helper function to rewrite regex to scan clauses
function prepare_regex(regexstr, P)

    # pull out the regex string and its args
    regex, args = length(regexstr) > 1 ?
        (regexstr[1], regexstr[2])     :
        (regexstr[1], nothing)

    # force a '^' at the regex start
    regex = regex[1] == '^' ?
        regex : "^" * regex

    # compile the regex
    r = isnothing(args) ?
        Regex(regex)    :
        Regex(regex, args)

    # produce the scan clause.
    @gensym x matched
    return quote
        $P.scan($x -> begin
            $matched = match($r, $x)
            isnothing($matched) && return 0
            return length($matched.match)
        end)
    end
end

function prepare_grammar(
    clauses,
    startrule,
    datatype,
    nowarn,
    __module__
)

    P = @__MODULE__
    startrule = @eval(__module__, $startrule)
    startrule = startrule isa Symbol ?
        [startrule] :
        startrule

    try

        # evaluate syntax rules
        pairs = map(clauses) do clause
            @eval(__module__, $(clause.first)) => 
                @eval(__module__, $(clause.second))
        end

        # build the grammar.
        g = make_grammar(
            startrule,
            flatten(
                @eval(__module__, Dict($pairs...)),
                @eval(__module__, $datatype)
            )
        )

        return g, :nothing

    catch e

        # we can only ameliorate bad symbol lookups here.
        e isa UndefVarError || rethrow()

        # warn the user that their symbols were unresolvable.
        # suppress during testing with unresolvable symbols.
        nowarn ||
            @warn "``$(e.var)``: Symbol not resolvable at macro time.\n\n"          *
                  "Evaluation of the grammar will be deferred to runtime.\n"        *
                  "Ensure that all symbols used in clauses are available at\n"      *
                  "the toplevel scope of module $__module__ for macro-time grammars."


        @gensym gram

        ids = map(x -> x.first,  clauses)
        def = map(x -> x.second, clauses)

        expr = quote
            $gram = $P.make_grammar(
                $startrule,
                $P.flatten(
                    Dict([$(ids...)] .=> [$(def...)]),
                    $datatype
                )
            )
        end

        return gram, expr.args[2]
    end
end


"""
    @syntax startrule datatype exprs [nowarn]

Define syntax of a grammar with rules given by `exprs`.

This produces a PikaParser grammar at compile-time,
and returns a function applying the grammar to
an input string. PikaParser symbols (`first`, `seq`, etc.)
will be resolved to the PikaParser module.

To build grammars at compile-time, all symbols must be
resolvable in the toplevel module. If this is not the case,
PikaParser will pass a warning to the user and attempt to
build the grammar at runtime. If this is intended behaviour,
the user may suppress the warning by setting `nowarn` to `true`.
Otherwise, no argument need be specified.

For example usage, we will parse a list of symbols from a string.

```julia
syn = P.@syntax :top begin
    :ws    => first(satisfy(isspace), epsilon)
    :ident => r"[a-z_]+[a-z0-9_]*"i
    :decl  => seq(:ident, :ws)
    :top   => some(:decl)
end

syn("foo Bar bA9Z QUx") # => PikaParser.ParserState
```

This returned function composes with the function
generated by @semantics to produce a complete parse:

```julia
sem = P.@semantics :top m v begin
    :ident => Symbol(m.view)
    :decl  => v[1]
end

syn("foo Bar bA9Z QUx") |> sem
    # => [:foo, :Bar, :bA9Z, :QUx]
```
"""
macro syntax(startrule, datatype, exprs::Expr, nowarn::Bool=false)

    clauses = []
    @gensym x

    P = @__MODULE__
    pika_syms = Dict(
        :satisfy            => :($P.satisfy           ),
        :scan               => :($P.scan              ),
        :token              => :($P.token             ),
        :tokens             => :($P.tokens            ),
        :epsilon            => :($P.epsilon           ),
        :ϵ                  => :($P.epsilon           ),
        :fail               => :($P.fail              ),
        :seq                => :($P.seq               ),
        :first              => :($P.first             ),
        :not_followed_by    => :($P.not_followed_by   ),
        :followed_by        => :($P.followed_by       ),
        :some               => :($P.some              ),
        :many               => :($P.many              ),
        :tie                => :($P.tie               ),
        :precedence_cascade => :($P.precedence_cascade),
        :end_of_input       => :($P.end_of_input      ),
    )

    # process the expressions.
    postwalk(exprs) do e

        # remove line number nodes.
        e = rmlines(e)

        # rewrite names
        e isa Symbol && return get(pika_syms, e, e)

        # rules for regex string (continue if no match)
        @capture(e, @r_str regexstr__) &&
            return prepare_regex(regexstr, P)

        # return if we don't have a syntax rule
        @capture(e, id_quote => clause_) ||
            return e

        # store the id and clause; return the ID
        push!(clauses, id => clause)
        return id
    end

    g, deferred_grammar_build = prepare_grammar(
        clauses,
        startrule,
        datatype,
        nowarn,
        __module__
    )

    return quote
        $deferred_grammar_build
        $x -> $P.parse($g, $x)
    end |> esc
end

"""
    @syntax startrule exprs [nowarn]

Shorthand for `@syntax startrule datatype exprs [nowarn]`
where `datatype` is set to `Char`.
"""
macro syntax(startrule, expr::Expr, nowarn::Bool=false)
    P = @__MODULE__
    return quote 
        $P.@syntax($startrule, Char, $expr, $nowarn)
    end |> esc
end

"""
    @semantics startrule match parsestate submatches exprs

Define semantics of a grammar with rules given by `exprs`.

This macro returns a function which can be applied to a
ParserState object, returning Julia datatypes as
defined by the semantic rules.

The start rule is given by `startrule`; the parameters
`match`, `parsestate`, and `submatches` are symbols which
will be bound to the current PikaParser `Match` object,
the current `ParserState`, and the liste of submatches.

Code given in the semantics is executed in the context of
a callback function to `traverse_match()`; local scopes may
be introduced, and early-return may be used to construct types.

Default behaviour is implemented for rules specified by
`@syntax` but not in `@semantics` for ease of parser bring-up,
so long as at least one semantic rule has been supplied by the user.
Terminal symbols (i.e., symbols where the submatch list is empty)
return their matching text (`match.view`). Nonterminal symbols
return their list of submatches. This allows developers to immediately
read out the resulting AST, and iteratively add semantic rules.

An example invocation is given here.

```julia
sem = P.@semantics :top m p v begin
    :ident => Symbol(m.view)
    :decl  => v[1]
end

```

The function returned from this macro composes with the
function returned by the "@syntax" macro; they are intended
to be used together. To continue this example:

```julia
syn = P.@syntax :top begin
    :ws    => first(satisfy(isspace), epsilon)
    :ident => r"[a-z_]+[a-z0-9_]*"i
    :decl  => seq(:ident, :ws)
    :top   => some(:decl)
end

syn("foo Bar bA9Z QUx") |> sem
    # => [:foo, :Bar, :bA9Z, :QUx]
```
"""
macro semantics(
    top::QuoteNode,
    match::Symbol,
    parsestate::Symbol,
    submatches::Symbol,
    exprs
)

    rules, x = Expr[], gensym(:x)
    P = @__MODULE__

    # process the semantic rules.
    postwalk(exprs) do e

        # match expressions of the form (symbol) => (rule)
        @capture(e, rule_quote => value_) || return e

        # rewrite semantic rule as if-statement.
        push!(rules, quote 
            if $match.rule == $rule
                $value
            else
                $submatches == [] ?
                    $match.rule => $match.view :
                    $match.rule => $submatches
            end
        end)

        return e
    end

    # rewrite the AST to chain the if statements.
    rules = reduce(reverse(rules)) do r1, r2
        r2.args[2].args[3] = r1
        r2
    end

    # generate the fold function.
    return quote
        $x -> $P.traverse_match($x,
            $P.find_match_at!($x, $top, 1),
            fold = ($match, $parsestate, $submatches) -> $rules
        )
    end |> esc
end

"""
    @semantics top match submatches exprs

Most users will not need to access the parse state when
bringing up semantics; the match view and submatches are
usually sufficient. This is a shorthand invocation of
`@semantics top match parsestate submatches exprs`
which binds `parsestate` to `_`.
"""
macro semantics(
    top::QuoteNode,
    match::Symbol,
    submatches::Symbol,
    exprs
)

    P = @__MODULE__
    return quote
        $P.@semantics $top $match _ $submatches $exprs
    end |> esc
end

"""
    @semantics top

If no rules are supplied to `@semantics`,
terminal syntax rules will be resolved to their
match views, and nonterminal rules will be
resolved to their list of submatches. Each resolution
is tagged as a `Pair` by the match rule.

This is useful for initial semantic rule bring-up and
validation of `@syntax` rules, and inspecting the AST.
"""
macro semantics(
    top::QuoteNode
)

    P = @__MODULE__
    @gensym match submatches x
    return quote

        $x -> $P.traverse_match($x,
            $P.find_match_at!($x, $top, 1),
            fold = ($match, _, $submatches) ->
                $submatches == [] ? 
                    $match.rule => $match.view :
                    $match.rule => $submatches
        )
    end |> esc
end
